name: Deploy static HTML from branches to GitHub Pages

on:
  push:
    branches:
      - main  
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages subfolder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: .   # Assuming your static HTML is in the root of each branch
          destination_dir: ${{ github.ref_name }} # deploy branch contents to subfolder with branch name

         